### ISSUE TITLE
Traversal Example

### ISSUE THREAD

**Issue by ThomasKrenn** [krotik/eliasdb#10]
Hello Matthias,
first off, I wanted to compliment you on the project you have created.
To help new users understand the concepts it be nice if you could provide an traveral example for the tutorial_data.
E.g. Show all Stations for Line something

Best regards
Thomas

**Comment by krotik** [comment]
Hi Thomas,

thanks, always nice to get compliments :-)

In the tutorial ([tutorial.md](https://github.com/krotik/eliasdb/blob/master/doc/tutorial.md)) is the following example:

```
We can see which stations are on the "Circle Line" by traversing the graph. Run a lookup query:

lookup Line "3" traverse Line:StationOnLine:Member:Station end
```

Following on there are a few more examples. Is that what you were looking for ?

**Comment by krotik** [comment]
I assume the existing example in the tutorial was sufficient. If not please reopen. Thanks.

**Comment by ThomasKrenn** [comment]
Hello Elias,
thanks for your response. 
Please add the tutorial to the "Further Reading" section.

Best regards
Thomas
