### ISSUE TITLE
Error on go get: can't load package: package devt.de/common

### ISSUE THREAD

**Issue by christophberger** [krotik/eliasdb#13]
I followed the steps in the README for downloading EliasDB but the first step

    go get -d -v devt.de/common devt.de/eliasdb

returns an error:

    can't load package: package devt.de/common: no Go files in /Users/christoph/go/src/devt.de/common

(which appears to be correct because devt.de/common only contains subpackages but not Go files.

I then tried

    go get devt.de/common/... devt.de/eliasdb/...

which succeeded and also built and installed `eliasdb` in `$GOPATH/bin`.  
Are the steps in the README still current? Did I overlook something?

**Comment by krotik** [comment]
Hi Christoph,

thanks for the heads up. You are right, your command line works better than the described one. I'll change the README file accordingly.
