### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by ivanjaros** [krotik/eliasdb#14]
I am looking for Go db that supports spatial data and I found only DGraph but after an hour of not being able to figure out how to fill it with data through their gql I gave up. And I found another graph db wirtten in Go - elias. Looking at the docs I don't see any mention of spatial data, so I take it there is none at this time?

Also, last commit is 2017 so I am guessing you have moved on to other things?

Lastly, any chance of using Badger as storage backend?

**Comment by krotik** [comment]
Hey there, I am currently working on a bigger update of EliasDB which I should hopefully finish very soon!

In the moment EliasDB does not support spatial data with specific features. What exactly are you planning to do? How can a graph database support this (or are you mainly interested in a fast storage backend)?

Optimizing indexing for spatial data might be not too difficult. Changing the query language to support spatial relationships might be a bit more tricky...

Different storage backends are definitely possible but it is not my current focus.
