### ISSUE TITLE
Invalid paths

### ISSUE THREAD

**Issue by thumbsized** [krotik/eliasdb#16]
I wanted to try this db with the memory example but it fails to run because it expects paths to be 
"devt.de/..." instead of "github.com/krotik/eliasdb/...".

You should update the project's structure so it can be used as library.

**Comment by Wulfheart** [comment]
May you provide a pull request?

**Comment by krotik** [comment]
Hi there,

the expected path devt.de/eliasdb/... is indeed correct. The code "lives" there - I do not use github as a primary code repository but merely as a mirror / backup.

I assume you did a `go get github.com/krotik/eliasdb/...` which results in many "unrecognized import path" errors. As described in the README.md under "Building EliasDB" do this:
`go get devt.de/common/... devt.de/eliasdb/...`
`go build devt.de/eliasdb/cli`

The code should be fetched with the correct paths.

PS: You will find that also golang uses github just as a mirror. See for example this code from their experimental packages: https://github.com/golang/exp/blob/master/shiny/driver/driver.go

**Comment by thumbsized** [comment]
I have since moved to DGraph but good to know.
