### ISSUE TITLE
Question: how to actually set up an eliasdb cluster?

### ISSUE THREAD

**Issue by beoran** [krotik/eliasdb#19]
I can see in the source code that there is some support for running eliasdb as a cluster. However, how should this be set up? It seems the CLi has no support for this.

**Comment by krotik** [comment]
Hello,

It is true that EliasDB can be run as a cluster. You can set the option `EnableCluster` in `eliasdb.config.json` to enable the cluster code. The feature is very much still experimental as I didn't have much time to test it at scale nor am I really confident that the replication works as expected.

If you are curious about the inner workings have a look at the `eliasdb_design.md` under DistributedStorage.

In the moment there is no support for the cluster via the CLI. However, there is a cluster terminal under `/web/db/cluster.html` if you enable the option `EnableClusterTerminal`.

**Comment by krotik** [comment]
The cluster as such is configured using a separate config file which is defined under `ClusterConfigFile` in `eliasdb.config.json`. Have a look at the cluster web terminal - it should possible to join multiple instances of EliasDB there. I didn't write any other documentation yet - sorry :-)
