### ISSUE TITLE
build and support arm binaries

### ISSUE THREAD

**Issue by c-nv-s** [krotik/eliasdb#23]
is it possible to build and include arm7 and arm64 binaries with your releases

**Comment by krotik** [comment]
Hey there, with version 1.1.0 there are now arm releases:

eliasdb_v1.1.0_arm7.tar.gz (ARMv7 - GOARM=7 | GOARCH=arm)
eliasdb_v1.1.0_arm8.tar.gz (ARMv8 - GOARCH=arm64)

Download them here: https://github.com/krotik/eliasdb/releases/tag/v1.1.0

Naming follows the table [here](https://github.com/golang/go/wiki/GoArm).

**Comment by c-nv-s** [comment]
Thanks I'll try and get around to testing it out :-)
