### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by lasarux** [krotik/eliasdb#29]
Tested in Linux and Mac.

--- FAIL: TestIndexManagerString (0.00s)
    indexmanager_test.go:766: Unexpected string output: IndexManager: 1
            1"aaa\b\xf8\xe0&\fdA\x85\x10\xce\xfb+\x06\xee\xe5\xcd" map[testkey:[]]
            1"aaabbb" map[testkey:[1]]

**Comment by krotik** [comment]
The fix in commit [3c4e9e4f9de925fbd41a95138c16dfc25cdfcc72](https://github.com/krotik/eliasdb/commit/3c4e9e4f9de925fbd41a95138c16dfc25cdfcc72) should fix this problem. It compiles now for me on Linux using Go 1.16.3 - I cannot test on Mac ... please let me know if it still doesn't work there.
