### ISSUE TITLE
tutorial demo - "Get Line fails on Term (browser) but not in Terminal CLI

### ISSUE THREAD

**Issue by gedw99** [krotik/eliasdb#33]
this code:
https://github.com/krotik/eliasdb/tree/master/examples/tutorial

# env
am on mac if it helps :)
golang 1.6.3

I am running this from dist directory BTW.

# Terminal 

it works 👍 

````
>>>get Line
┌─────────┬────────────────────────┐
│Line Key │Line Name               │
│1:n:key  │1:n:name                │
├─────────┼────────────────────────┤
│10       │Piccadilly Line         │
│13       │Docklands Light Railway │
│12       │Waterloo & City Line    │
│11       │Victoria Line           │
│8        │Metropolitan Line       │
│1        │Bakerloo Line           │
│2        │Central Line            │
│3        │Circle Line             │
│9        │Northern Line           │
│5        │East London Line        │
│7        │Jubilee Line            │
│6        │Hammersmith & City Line │
│4        │District Line           │
└─────────┴────────────────────────┘
>>>

find liverpool
Partition main
Kind      Station
┌─────────┬────┬────────┬─────────┬──────────┬─────────────────┬─────┐
│has_rail │key │kind    │latitude │longitude │name             │zone │
├─────────┼────┼────────┼─────────┼──────────┼─────────────────┼─────┤
│true     │156 │Station │51.5178  │-0.0823   │Liverpool Street │1    │
└─────────┴────┴────────┴─────────┴──────────┴─────────────────┴─────┘


````

# Term browser 

same query fails 👎 

![Screenshot 2021-05-17 at 13 07 04](https://user-images.githubusercontent.com/53147028/118479000-cd7fda00-b710-11eb-82c5-135b9e0cb720.png)

**Comment by krotik** [comment]
I haven't done development on the web terminal for quite some time. The CLI terminal has a lot more functions. The problem here is that you switched to the partition "get line" with the statement `part get line` so when you try to query for `Line` nodes the REST API responds that the partition name is invalid. Both the error message and the terminal need some work :pensive:

**Comment by gedw99** [comment]
ok fair enough..  Will stick with terminal :)

I am going to make a new issue about an idea i have for the Web Terminal...

**Comment by gedw99** [comment]
here is the idea: https://github.com/krotik/eliasdb/issues/35

**Comment by gedw99** [comment]
I just realised I did not read what your said properly about the ordering . Was tired ..
now it all makes sense :)

will play with it some more
