### ISSUE TITLE
godoc not allowing cross searching

### ISSUE THREAD

**Issue by gedw99** [krotik/eliasdb#7]
you are using a different go docs ? I was hoping to check how many other projects are using eliasdb, but i cant do that with your project.

https://godoc.org/?q=github.com%2Fkrotik%2Feliasdb

**Comment by krotik** [comment]
Hi,

the code is hosted on my own server using gogs (https://gogs.io/docs). The godoc link is:

[https://godoc.org/devt.de/eliasdb](https://godoc.org/devt.de/eliasdb)

Unfortunately, it is not possible to explore sub packages - I am not sure why though ... I assume there is a special way godoc crawls the repositories...

**Comment by krotik** [comment]
Unfortunately, I haven't found a way to make this work. Let me know if you find anything ...

**Comment by gedw99** [comment]
Ok fair enough.
I am building a facet search system for golang code now. It will allow this type of search.

It's using bleve of course.

When it's done I will publish it
